### ISSUE TITLE
chapter7

### ISSUE THREAD

**Issue by bingohuang** [hantmac/Mastering_Go_Second_Edition_Zh_CN#20]
### 领取的章节
chapter7

### 翻译的大致的DDL
7.31

### 讨论的关键点
`Reflection`、`Interfaces`

**Comment by bingohuang** [comment]
chapter6(#18)正在着手翻译中，发现和 chapter7 内容有所关联，也很实用，也一起申领了~

**Comment by lyuzizheng** [comment]
什么时候完成呢？没时间的话我过一段时间也可以领取
